name = "DZOptimization"
uuid = "7e4c8b08-07ea-4d35-9260-462b5bfff2a0"
authors = ["David K. Zhang <dzhang314@gmail.com>"]
version = "0.6.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
KernelAbstractions = "^0.9.34"
julia = "^1.10"
