name = "DZOptimization"
uuid = "7e4c8b08-07ea-4d35-9260-462b5bfff2a0"
authors = ["David K. Zhang <dzhang314@gmail.com>"]
version = "0.1.0"

[deps]
DZLinearAlgebra = "6f20c22c-3052-42e0-aac1-b2428640d1cc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
